### DISCUSSION TITLE
Material Sync (docs folder to versions)

### DISCUSSION THREAD

**Discussion by lebalz** [GBSL-Informatik/teaching-dev#162] [General]
Let's discuss how we want to specify, which docs-folders shall be synced to which versions folders...
It is more about the format and the capabilities and less about the implementation.

What i would like is a format, that is
- easy to understand by looking at the content
- easy to edit by hand
- can sync single files
- can sync folders
  - recursivley
  - excluding parts of the folder
- can sync a folder from a specified remote url, e.g. a git repository

A possible structure could look like this:
```
sync
├── 26Gb.sync.yaml
├── 28Gj.sync.yaml
└── 28Gb.sync.yaml
```

and a sync file could look like that

```yaml
items:
- dir:
    from: docs/OF-Programmieren1
    to: 01-Praktikum/Programmieren1
    exclude:
    - lernziele
    - index.mdx
    open: true
- file:
    from: docs/OF-Programmieren1/lernziele/v28.mdx
    to: 01-Praktikum/Programmieren1/lernziele.mdx
- remote:
    url: https://github.com/SilasBerger/teaching-website.git
    ref: main
    from: docs/material/IN-Biber/2024
    to: docs/02-Informatik-Biber
    exclude:
    - Übungen.mdx
```
